apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-app
  namespace: shipping
spec:
  # replicas: 2 # updated 2 for HA
  selector:
    matchLabels:
      app: shipping-app
  template:
    metadata:
      labels:
        app: shipping-app
      annotations:
        description: "Deployment for the smart-health application"
    spec:
      containers:
        - name: shipping-app-container
          image: errorhunter/smart-health-monitoring-app:c1307f6a8325bc06e1114f19f47e16d8c4297b29
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          # envFrom:
          #   - configMapRef:
          #       name: smart-health-configmap
          #   - secretRef:
          #       name: smart-health-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 3